#%RAML 1.0
title: SF-mule-SyAPI

types: 
    ContactObject: !include examples/ContactObject.json
    
  
/contactDetails:
    get:
     queryParameters:
          email: string
     responses:
       200:
          body:
             application/json:
                type: ContactObject
                examples:
                  output: !include common/contact.raml
                
                
                 
             
    

